### ISSUE TITLE
IE.exe/MS(X)HTML.dll/MSHTTP.dll integration needed

### ISSUE THREAD

**Issue by Ruedii** [madewokherd/wine-mono#17]
Many apps currently need IE integration.

As far as I know there are two options:
1. embed the current IE substitute
2. write a replace the current IE substitute with a new one built into Wine-Mono.

The first option would be more in line with how Windows XP works, but the second would be more in line with how Windows Vista, 7 and 8 work.  (Windows 7 being the main one to be concerned with.)  However, either option would technically work.

**Comment by HinTak** [comment]
I was going to file a new issue for my pull ( https://github.com/mono/mono-webbrowser/pull/1 ) to be looked at, but this is related and would do too. I have revived mono's webkit winform alternative to libgluezilla. See 

https://bugs.winehq.org/show_bug.cgi?id=30988#c10
and
https://github.com/HinTak/mono-webbrowser

basically just build it, put webkit-sharp & win32 version of webkitgtk and its dependencies into the current directory, I got win32 mono to launch a dotnet winform web browser . So you could probably use this info to fix https://bugs.winehq.org/show_bug.cgi?id=30988 with a little extra.

The 2 problems I had with getting the webkit backend working with win32 mono are:

- there are some strange missing symbols and incompatibility btween libstdc++ and libcairo shipped by win32 mono and those from the cross-compiled mingw32 dll's I have from fedora. I needed to move them aside and put those from fedora in. (presumably fedora's are newer and have more symbols). Presumably you can solve this by building win32 mono and webkitgtk the same way...

-   https://github.com/HinTak/mono-webbrowser/issues/1

and a 3rd from wine-mono vs win32 mono: I can't get wine-mono to give me any reason why it doesn't like what I was doing, compared to win32 mono. Win32 mono at least tells me it is missing dlls, not liking symbol missing, etc.

HTH.

**Comment by HinTak** [comment]
BTW, I think mshtml com interop already works with gecko ? It is system.windows.forms.browser which needs libgluezilla, which does not work ( https://bugs.winehq.org/show_bug.cgi?id=30988 )

**Comment by madewokherd** [comment]
I'm not going to ship webkit with wine-mono. It's just as wrong as libgluezilla.

**Comment by HinTak** [comment]
Fair enough - I think webkit is a bit big, given there is already gecko. Anyway, another bridge through the mono-webbrowser 'secret hand shake' with gecko may do too.

**Comment by Ruedii** [comment]
Considering that Edge is mostly utilizing .Net based components now.  (It is still a hybrid of C/C++ and .Net) there is no reason we can't follow the same route and make an alternative IE/MSHTML interpretation in full Mono.   As long as it has the appropriate C/C++ hooks it'll probably work better.  The only issue is we have to make sure it works on the Microsoft .Net implementation of ECMA CIL as well as the Wine Mono implementation.  This is important, because the two can't currently coexist yet.  (Probably something else that should be addressed.)

**Comment by madewokherd** [comment]
We already have an alternative IE/MSHTML implementation in Wine, why would we want to build a new one for Mono?

**Comment by HinTak** [comment]
Perhaps you got it backwards. .net has a big name space System.Windows.Forms.WebBrowser(), and many .net applications depends on it to provide an embedded webbrowser, or even just a document viewer. On genuine windows with genuine .net, SWF.webbrowser is implemented through mshtml.dll . On wine with genuine .net,  application can use the gecko provided mshtml too. Subjected to subtle difference between the two (e.g. Genuine mshtml will load local css from disk, gecko mshtml won't).

However, if one wants to be free as in libre, wine-mono does not provide adequate support for SWF.WebBrowser, vs genuine dotnet runtime. The problem is wine-mono cannot currently make use of wine-gecko to provide SWFW. Also, wine-gecko is a wine-specific answer, and unlikely to be useful to other mono usage where wine is not involved.

I hope this is clearer? So mono needs a better (cross-platform) SWFW implementation, and wine-mono needs better integration with wine-gecko . It is just a pity that the two tasks share very little in common, although they try to achieve more or less the same goal: better support for the SWF.WebBrowser name space for mono/wine-mono.

**Comment by madewokherd** [comment]
If Mono's winforms is updated with an MSHTML backend, Mono benefits on Windows too.

There would be a compatibility benefit for Mono if it had a cross-platform renderer compatible with MSHTML. There are a lot of cases like this, where they end up duplicating something that's in Wine. Mono includes implementations of some kernel32 functions and a full gdiplus implementation. (FWIW, it still makes me sad that there was no cooperation between Wine and Mono in reimplementing gdiplus.)

However, I think you're underestimating the amount of work it took to get wine-gecko and mshtml to the point where it is now, and the amount of work still left to do on those components. I can't imagine rebuilding that from scratch.

I also don't think Mono is interested in the level of compatibility that Wine demands. I don't see them wanting ActiveX or MHTML support on Linux, for example, but Wine needs those things.

**Comment by Ruedii** [comment]
I'm suspect a large part of what is making this so hard to implement has to do with the Wine IE and MSHTML implementation.

**Comment by madewokherd** [comment]
We now use winforms from .NET core which uses MSHTML.

**Comment by SugarRayLua** [comment]
Dear @Ruedii and @madewokherd,

I was curious as to whether there has been any more work on WINE IE as was discussed previously in this forum. I'm having difficulty installing WordPerfect 2021 in wine and suspect that it is related to differences between WINE IE and Windows IE (specifically regarding Wine IE's inability to handle javascripts). The current WordPerfect installation involves initiating the installations with an .exe installation file the user purchases (which runs fine), but subsequently the installer then connects to the internet from inside Wine and attempts to download further files to finish the installation which does not work. I suspect it is due to the WordPerfect installer somehow calling IE (which ends up being WINE IE) due to error message it produces which says that I don't have javascript enabled (despite having attempted the installation with new Wine versions and even on ReactOS/VirtualBox using working Firefox & K-Meleon as my default browsers). 

I'm a novice programmer/Wine/Windows user (I primarily use Linux) and realize I maybe misunderstanding the problem or its relationship to this issues but as I've written the WordPerfect developers (Corel) and not yet gotten a response, I was interested in any additional thoughts or suggestions you might have on my concern that the difficulty in the WordPerfect installation might be related to WINE IE's inability to run javascript. 

Thanks! :-)

**Comment by SugarRayLua** [comment]
Thank you very much, @HinTak :-). I've got the Wine Guis: Bottles, Lutris, and Heroic Launcher set up on my system and tried to use those but wasn't successful at installing MSHTML (internet explorer) or Microsoft Edge. I was able though to install install MSHTML 6 using a playonlinux script. Unfortunately, WordPerfect 2021 seems to need MSHTML 11, and I wasn't successful in being able to install that using playonlinux, as I would get Microsoft messages telling me I needed to first get additional MSHTML 11 updates before it would install (and wasn't able to get any Microsoft Edge version to install [32 nor 64 bit and not with Wine set to Windows 7, 8.1 or 10]. I left a message on the playonlinux forum to see if anyone there might be able to help; otherwise, I'll try setting up Wine without a Gui and use winetricks as you suggested. 

P.S.,
Do you happen to know if there is any registry key I could set to tell Windows programs running in Wine (e.g. WordPerfect) to open a browser besides MSHTML/winebrowser when it encounters html/javascript?

**Comment by HinTak** [comment]
@Ruedii I wrote winestricks and I meant it https://github.com/Winetricks/winetricks . As for the rest of your questions, I have no clue. I don't have anything to add beyond what I already wrote: the "default" mshtml implementation in wine is gecko based, and that does not include a javascript runtime. You can override the gecko-based mshtml by installing "genuine" mshtml from Microsoft, via winetricks is possibly your best bet.

**Comment by HinTak** [comment]
I just had a quick look inside winetricks - it should let you install ie 7 or ie 8, in addition to the rather old ie 6.

Btw, winetricks is a GUI program! It autotects and switch into GUI mode under some circumstances. (Mainly if you don't know what you want, winetricks will launch a GUI with a list plus buttons next to the items).

**Comment by SugarRayLua** [comment]
Cool, thanks, @HinTak , I'll try out winetricks! :-)
