### ISSUE TITLE
[info] force winefrefix upgrade when newer wine-mono is installed (4.8.1+)

### ISSUE THREAD

**Issue by sl1pkn07** [madewokherd/wine-mono#47]
Hi

i need some info for how upgrade the wine-mono 4.8.1+ if newer version is installed

i have installed the wine-mono 4.8.1 from wine-mono-bin-4.8.1.tar.gz in the specified path (/usr/share/wine/mono) but when launch a new instace of wine, wine mono is not upgraded from older msi method to new shared method

and today, when i've installed the new version 4.8.3, the wine-mono is not upgrade from 4.8.1 to 4.8.3

how i can force the upgrade when launch wine?

i have wine-staging 4.6.0 builded from GIT

greethings

**Comment by sl1pkn07** [comment]
ok. seems still need v4.8.1, acording by this https://source.winehq.org/git/wine.git/commitdiff/dc2c580bdfab2b6850241afae66d7dee5db94c0e?hp=179797a6fb7b609e86f5c9767bf5349a8015e388, no other newer version is pushed

and i able to reinstall mono if do `wineboot -u` after remove the folder mono in `c;\windows\` and remove the installers from  `c:\windows\installer` and `$HOME\.cache\wine`

case closed(?)

greetings

**Comment by madewokherd** [comment]
It's a known bug that it doesn't automatically update to the shared install. That should be fixed in the next release.

For now, if you remove the old version and run 'wine64 regsvr32 mscoree' it should find and set up the new one. Running that command with WINEDEBUG=mscoree will give more information about what it's doing.

Note that Wine's search path for the shared version includes the version number, so right now it looks for /usr/share/wine/mono/wine-mono-4.8.1. If you want to try 4.8.3 before Wine is updated, the easiest way is probably to install the msi. You can also set a string value named RuntimePath in HKEY_CURRENT_USER\Software\Wine\Mono to the path in Windows format.

Sorry for the trouble, I made several mistakes when implementing this.

**Comment by madewokherd** [comment]
You shouldn't have to remove the mono folder. Did the uninstaller break?

**Comment by sl1pkn07** [comment]
i do that in one of my test, i can remove the wineprefix and do all again

**Comment by sl1pkn07** [comment]
tested with other older prefixes. the update from older wine-mono to new shared wine-mono method is finished without problem, the "strange" is, the mono folder is still here. is ok?

**Comment by madewokherd** [comment]
What do you have in wine uninstaller after the update?

**Comment by sl1pkn07** [comment]
`wine mono windows support`
![Screenshot_20190420_013558](https://user-images.githubusercontent.com/462213/56448071-a75a9680-630c-11e9-9a9b-dc0dd1c28214.png)

**Comment by madewokherd** [comment]
Yeah, that should really have removed the mono folder.

**Comment by madewokherd** [comment]
Depending on how old the prefix was, it may have some leftovers from when we were replacing packages wrong. Maybe we shouldn't worry about it.

**Comment by sl1pkn07** [comment]
ok then. i can wait to upstream for update wine-mono for update to 4.8.2+

then is safe deleting the mono folder by hand?

**Comment by madewokherd** [comment]
Should be fine. I am curious which files are left.

**Comment by sl1pkn07** [comment]
in this prefix:

[list_leftovers.txt](https://github.com/madewokherd/wine-mono/files/3099576/list_leftovers.txt)

**Comment by madewokherd** [comment]
Thanks. Just from a quick glance, I think these are all old files that we don't ship anymore. It's unfortunate, but I don't think there's a clean fix, and as long as the libmono dll files aren't present in bin, it shouldn't hurt anything. Recent prefixes shouldn't produce those orphaned files anymore.

**Comment by sl1pkn07** [comment]
thanks for the info

greetings
