### ISSUE TITLE
Threadpool tests don't work

### ISSUE THREAD

**Issue by madewokherd** [madewokherd/wine-mono#62]
From master branch:

```
wine tests/run-tests.exe MonoTests.System.IO.Pipes.PipeSecurityTest:NamedPipePermissionsActuallyWorkAsync
```

results in this exception:
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at System.Threading.ThreadPoolCallbackWrapper.Exit (System.Boolean resetThread) [0x00003] in <69b37f4109d4441883f55c2e386a376b>:0 
  at System.Threading.ThreadPoolBoundHandle.OnNativeIOCompleted (System.IntPtr instance, System.IntPtr context, System.IntPtr overlappedPtr, System.UInt32 ioResult, System.UIntPtr numberOfBytesTransferred, System.IntPtr ioPtr) [0x00039] in <69b37f4109d4441883f55c2e386a376b>:0 
  at (wrapper native-to-managed) System.Threading.ThreadPoolBoundHandle.OnNativeIOCompleted(intptr,intptr,intptr,uint,uintptr,intptr)
Test failed(couldn't read test results): x86.MonoTests.System.IO.Pipes.PipeSecurityTest
```

This test used to fail, but now that Wine implemented CreateThreadpoolIo, I think it is using a broken codepath in Mono. ThreadPoolCallbackWrapper makes use of RuntimeThread.InitializeThreadPoolThread() and .ResetThreadPoolThread(), but in Mono's version of RuntimeThread these are stubs.

These tests are skipped on Linux Mono, so it seems they're not expected to work upstream? So this may be a case where the fix can go upstream as well. Mainly creating the issue to document what I know about it.

**Comment by w-flo** [comment]
Hi Esme, nice to meet you again :-)
This bug might be https://github.com/mono/mono/issues/17994 – I posted a workaround I used back then in that issue. This is a blocker to get an important feature in ZUSI 3 - Aerosoft Edition working, though they plan to change the way this feature works for the next update, so who knows.

Right now I'm trying a different workaround that doesn't modify the external corert repo, but I'm having issues building wine-mono 5.0, it complains about missing libgdiplus during "resgen Resources/Documents.resx Resources/Documents.resources". So I wasn't able to test that workaround yet. Anyway, this is what I'm trying to compile:
```diff --git a/mcs/class/corlib/corert/RuntimeThread.cs b/mcs/class/corlib/corert/RuntimeThread.cs
index 064aefed9d0..97efa6692c7 100644
--- a/mcs/class/corlib/corert/RuntimeThread.cs
+++ b/mcs/class/corlib/corert/RuntimeThread.cs
@@ -14,7 +14,7 @@ sealed class RuntimeThread
                
                public void ResetThreadPoolThread () {}
                
-               public static RuntimeThread InitializeThreadPoolThread () => default;
+               public static RuntimeThread InitializeThreadPoolThread () => new RuntimeThread (null);
 
                public static RuntimeThread Create (ParameterizedThreadStart start, int maxStackSize) 
                        => new RuntimeThread (new Thread (start, maxStackSize));
@@ -45,4 +45,4 @@ public static int GetCurrentProcessorId ()
                        return 1;
                }
        }
```
The problem appears to be that InitializeThreadPoolThread() returns default (which is probably null – zero modern C# experience here). The ThreadPoolCallbackWrapper then calls a method on that null reference in Exit().

**Comment by madewokherd** [comment]
Yeah, you'll need to install libgdiplus. It's needed for the winforms build process.

**Comment by w-flo** [comment]
Thanks, I didn't know it's available from the apt repository just like that. I also had to adjust xaml2cs to use the Invariant culture (because my culture uses "," in floats instead of ".") `Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;`.

Now it builds and the workaround posted above seems to work for my use case. Performance is not great, but that's probably unrelated.

I'm not sure if I should open a PR against mono, as it seems like a hack. Probably still better than the previous hack.

**Comment by madewokherd** [comment]
Please open a PR against my fork of wpf here: https://github.com/madewokherd/wpf

It's my hack and doesn't exist upstream. A proper tool for this would be nice, but to my knowledge no such thing exists in a usable form.

**Comment by w-flo** [comment]
Oh I'm sorry, I didn't mean to call wpf or xaml2cs a "hack". I was actually referring to the diff I posted above, which is clearly a hack, because it passes a null Thread into the RuntimeThread constructor. But it might be better than the previous mono hack, which was "InitializeThreadPoolThread() returns null".

My hack works for me, but this probably needs further investigation to find a solution that is acceptable for mono.

**Comment by madewokherd** [comment]
I have rediscovered the original bug around CreateThreadpoolIo, and it reminded me that LiveSplit also uses this.

**Comment by w-flo** [comment]
For the record, with the one-line change to RuntimeThread.cs from my first comment, the `MonoTests.System.IO.Pipes.PipeSecurityTest:NamedPipePermissionsActuallyWorkAsync` test runs without throwing the same exception. It fails a test assertion instead, but that could be unrelated to wine-mono and simply a missing wine feature(?):
```
  Client was allowed to connect despite Deny ACE.
  Expected: True
  But was:  False
```

**Comment by w-flo** [comment]
I have now submitted a mono PR, let's see what they think about it: https://github.com/mono/mono/pull/19782

**Comment by w-flo** [comment]
The PR was merged, so this specific NullReferenceException should hopefully be fixed upstream. The NamedPipePermissionsActuallyWorkAsync test will probably still fail because of the "Deny ACE" issue above.

**Comment by madewokherd** [comment]
Fixed in 5.1.0, thank you for your work on this.

**Comment by madewokherd** [comment]
Thanks again, you helped make this possible https://twitter.com/madewokherd/status/1274074775879585792

**Comment by w-flo** [comment]
Well, thanks for cherry-picking my "-1 +2 words patch" :-) I'm not sure what livesplit does, but it seems to be used for speedruns, so that's great.

For me, this change fixed ZusiDisplay integration in Zusi 3, which is great. However, gdiplus and especially gdi32 seem to have major performance issues (with gdi32 querying X display resolution and gamma registry keys all the time), and ZusiDisplay makes heavy use of gdiplus. It also doesn't seem to handle back-pressure at all, so instead of skipping frames the display lag appears to grow indefinitely, which is not great in a game/simulation where ZusiDisplay might be responsible for displaying the current speed. So maybe I'll try to get some gdi performance patches accepted into wine next. It also uses async IO and named pipes a lot (though that might change in the next update), so the wineserver stuff makes it quite heavyweight anyway. :-) This game is a beast.
